### PR TITLE
Convert all idents in grammar to identNode

### LINKED ISSUE #112: Consider when module path is on a separate line.
Consider when module path is on a separate line. Use the identifier's location in the jison-file.

_Originally posted by @maskmaster in https://github.com/kolint/kolint/pull/97#discussion_r524545804_

### LINKED ISSUE #113: Multiple as expressions in import doesn't work
**Current behavior**
KOLint only emits "typeof" type for the first alias import ("as import")

### PR DESCRIPTION
**Pull request by tscpp**
Most of all, identifiers in grammar.jison are defined without location. I added the IdentifierNode to the parser's YY and used it in the view model and binding handler refs. It can be added to all nodes in the feature but is not necessary for the time being.

Fixes #113 
Fixes #112

### CODE REVIEW

File: src/compiler/emit.ts [hunk 1]
```diff
@@ -223,9 +233,9 @@ function emitBHImportStatements(refs: BindingHandlerImportNode[], sourcePath: st
 	const bindinghandlers = refs.map(ref => {
 		if (!ref.imports) return
 
-		const entries = Object.entries(ref.imports)
+		const entries = Object.entries(ref.imports.value)
 
-		return entries.map(entry => entry[1]).map(alias => `'${alias.value}': BindingContextTransform<bindinghandler_${alias.value}>`)
+		return entries.map(entry => entry[1]).map(alias => `'${alias.name.value}': BindingContextTransform<bindinghandler_${alias.name.value}>`)
```
Comment (tscpp) [inline src/compiler/emit.ts:238]: use `ref.imports.value` directly

**Comment by tscpp** [comment]
Merge when approved

**Review by maskmaster — APPROVED** [review]
