### PR TITLE
Major rewrite of code generation and source mapping

### LINKED ISSUE #17: Support for multiple view model imports
https://github.com/kolint/kolint/blob/6f78315210bfb37ce740014b11f6a69e19b06f30/src/compiler/emit.ts#L82-L83

Currently, only the first one is emitted. Add support for emitting multiple view model imports.

### LINKED ISSUE #45: View without viewmodel
**Current behavior**
If no view model is linked, KO Lint will throw this:
```typescript
Diagnostic {
  location: undefined,
  code: 'KO0002',
  message: 'Missing ViewModel reference in file ',
  name: 'no-viewmodel-reference',
  severity: 3
}
```

**Expected behavior**
To be able not to have linked a view model or suppress the error in some way.

**Steps to reproduce**
```typescript
import * as lint from '...'

;(async () => {
	try {
		const program = lint.createProgram()

		await program.typescriptCompiler.compile('', program.parse('<img data-bind="test: undefined">'))
	} catch (err) {
		if (err instanceof Error)
			throw err

		// Will end up here
		console.log(err)
	}
})()
```

### LINKED ISSUE #75: CLI: Warn when input file does not exist
**Current behavior**
In  CLI when referencing a file that does not exist, the linter finishes without any errors.

**Expected behavior**
Warning message about missing input file.

### LINKED ISSUE #82: Binding handler diagnostic end position too long
**Current behavior**
image

**Expected behavior**
The diagnostic should've ended 2 column positions ago.

**Steps to reproduce**
```
<span data-bind="test: valid"></span>
```

### LINKED ISSUE #147: Import default and block in same import statements
**Current behavior**
Trying to use `import x, { y } from '\'` results in an exception.

**Expected behavior**
Be able to use  `import x, { y } from 'z'` .

**Steps to reproduce**
```
<!-- ko-bindinghandler: import x, { y } from 'z' -->
```

### PR DESCRIPTION
**Pull request by maskmaster**
* Optimize the compilation flow to take advantage of typescript's incremental parsing.
* Change to append-only when generating code and inferring types. Only standard typescript APIs used.
* Update grammar and code to new syntax for managing binding contexts (ko-import, ko-context and ko-viewmodel)
* Handle multiple named imports
* Add "typeof" support for viewmodel references
* Add support to modify the current context. Type hints make it possible to assert "magical" binding handlers where it is not possible to infer the type. E.g. Durandal's binding handler "Widget".
* Add support for analyzing multiple files at a time
* Move emit responsibilities to SourceBuilder
* Add revision control in the SourcBuilder to support the incremental updates (enables the generational source mapping)
* Filter out properties that are not valid variable names. (work around until we can support all possible property names)

* Use latest released typescript
* Upgrade packages and update code accordingly.

* Improved error reporting.
* Add support for $index and $parentContext to binding context types.
* Keep better track of diagnostic's originating file

* Fix typing for 'foreach' bindings (handle the 'as' property)
* Fix source map references for all transformed identifiers
* Fix diagnostic output with source mapped positions.

Fixes #147
Fixes #82
Fixes #75
Fixes #45
Fixes #17

### CODE REVIEW

File: demo/resources/bindinghandler.ts [hunk 1]
```diff
@@ -1,8 +1,6 @@
-import ko from 'knockout'
-import { BindingContext, ChildBindingContext, Overlay } from '../../lib/resources/context'
+import { BindingContext, ChildBindingContext } from '../../lib/resources/context'
 type koko<Value = string[]> = {
```
Comment (tscpp) [inline demo/resources/bindinghandler.ts:2]: Rename to a binding handler name that makes sense. Maybe `test`?

File: lib/resources/context.d.ts [hunk 2]
```diff
@@ -1,48 +1,37 @@
+/// <reference lib="dom" />
 /* eslint-disable @typescript-eslint/ban-types */
 /* eslint-disable @typescript-eslint/no-explicit-any */
+import 'knockout'
```
Comment (tscpp) [inline lib/resources/context.d.ts:4]: What does this do? I think these kinds of imports are not effecting the types.

File: lib/resources/context.d.ts [hunk 3]
```diff
@@ -129,31 +121,38 @@ export interface StandardBindingContextTransforms {
...
-	// Since we do not have support for const string types in Typescript yet (see https://github.com/microsoft/TypeScript/issues/30680), we resort to simpler matching here and instead
-	// we do more comprehensive analysis for 'foreach' bindings in-code instead.
-	foreach: <Value extends MaybeReadonlyObservableArray<any> | MaybeReadonlyObservable<any>, Context extends BindingContext<any, {}>>(value: Value, parentContext: Context) =>
-		Value extends Record<'as', infer T> & Record<'data', MaybeReadonlyObservableArray<(infer V)>> ?
-			T extends string ? BindingOverlay<Record<T, V>, Overlay<ChildBindingContext<V, Context>, Context>> :
+	// Since we do not have support for const string types in Typescript yet (see https://github.com/microsoft/TypeScript/issues/30680), we resort to a complex type 'Narrow' to make sure
+	// it is not widened to a string. Inspiration from ts-toolbelt.
+	foreach: <Key, VM, Context extends BindingContext>(value: { data: MaybeReadonlyObservableArray<VM>, as: Narrow<Key> } | MaybeReadonlyObservableArray<VM>, parentContext: Context) =>
+		Key extends string ? string extends Key ?
 			'\'as\' must be a string literal' :
```
Comment (tscpp) [inline lib/resources/context.d.ts:137]: Cannot the generic type `Key` extend `string`. If so the `'\'as\' must be a string literal'` is unnecessary, because it will `never` happen.

File: spec/src/spec.ts [hunk 4]
```diff
@@ -48,126 +54,100 @@ const parseTests = {
...
+
+	// 	() => {
+	// 		const diags = correctPositionEmitCache
+
+	// 		return (diags.length === 4 &&
+	// 		diags[2].location?.coords?.first_column === 16 && diags[2].location?.coords?.last_column === 20 &&
+	// 		diags[2].location?.coords?.first_line === 3 && diags[2].location?.coords?.last_line === 3) ||
+	// 		'Invalid start and end positions'
+	// 	}
+	// ],
```
Comment (tscpp) [inline spec/src/spec.ts:150]: Is this needed anymore?

File: spec/src/spec.ts [hunk 5]
```diff
@@ -48,126 +54,100 @@ const parseTests = {
...
-		]
 	]
 }
 
-let correctPositionEmitCache: readonly lint.Diagnostic[] = []
-// Do not change this unsless you know what you are doing!
-const emitTestString = '<!-- ko-viewmodel: import default from \'nothing2\' -->\n<img data-bind="test: undefined">\n<img data-bind="text: notdefined">'
+// let correctPositionEmitCache: readonly lint.Diagnostic[] = []
+// // Do not change this unsless you know what you are doing!
+// const emitTestString = '<!-- ko-viewmodel: import default from \'nothing2\' -->\n<img data-bind="test: undefined">\n<img data-bind="text: notdefined">'
```
Comment (tscpp) [inline spec/src/spec.ts:110]: Is this needed anymore?

File: src/cli/cli.ts [hunk 6]
```diff
@@ -90,85 +89,65 @@ async function glob(pattern: string) {
...
-	fs.mkdirSync(dirname)
-}
-
 async function main() {
-	const files = (await Promise.all(yargs.argv._.map(async pattern => glob(pattern)))).flat()
-	const filesFolder = getContainingFolder(files)
+	const files = (await Promise.all(yargs.argv._.filter((option): option is string => typeof option === 'string').map(async pattern => glob(pattern)))).flat()
+	if (files.length === 0) {
+		console.error('No matching file(s)')
+		process.exit(-1)
```
Comment (tscpp) [inline src/cli/cli.ts:96]: Why -1?

File: src/compiler/SourceBuilder.ts [hunk 7]
```diff
@@ -0,0 +1,153 @@
...
+	}
+
+	/**
+	 * Load scaffold into a source file
+	 */
+	private createScaffold(): string {
+		const linterLibPath = path.resolve(__dirname, '../../lib/resources/context')
+		return [
+			// '/* eslint max-len: 0 */',
+			// '/* eslint @typescript-eslint/no-unused-vars: 0 */',
```
Comment (tscpp) [inline src/compiler/SourceBuilder.ts:55]: Not used anymore?

File: src/compiler/SourceBuilder.ts [hunk 8]
```diff
@@ -0,0 +1,153 @@
...
+
+	// public emitTypeDefinition(ancestorContext: BindingContext, binding: Binding): void {
+	// 	const definitions = binding.map((child) => {
+	// 		const type = child.typeAssertion
+	// 		return type ?
+	// 			`const ${child.id}: ChildBindingContext<${type}, typeof ${child.parent?.id ?? 'unknown'}> = undefined\n` :
+	// 			`const ${child.id} = transformation_${binding.identifierName}(${child.parent?.id ?? 'unknown'})\n`
+	// 	})
+	// 	this.currentNode.add(definitions)
+	// }
```
Comment (tscpp) [inline src/compiler/SourceBuilder.ts:152]: Is this needed anymore?

File: src/parser/index.ts [hunk 9]
```diff
@@ -2,5 +2,5 @@ import './polyfill'
 export { parse } from './parser'
 export { Reporting } from '../program'
 export { Diagnostic, Severity } from '../diagnostic'
-export { Binding, BindingData, BindingExpression, BindingName, DiagNode, Document, Node, NodeType, ViewModelNode } from './bindingDOM'
+export { Binding, BindingData, BindingExpression, BindingName, DiagNode, Document, Node, NodeType, ImportNode as ViewModelNode } from './bindingDOM'
```
Comment (tscpp) [inline src/parser/index.ts:5]: Why as?

**Review by tscpp — CHANGES_REQUESTED** [review]

File: src/cli/cli.ts (hunk 6 above)
Comment (maskmaster) [reply src/cli/cli.ts]: Changed to 2

**Review by tscpp — APPROVED** [review]
